### ISSUE TITLE
SyntaxError: Unexpected token .

### ISSUE THREAD

**Issue by parakawa** [iamdanieloh/friender#1]
And I installed all the dependencies in my local. When I run the application, I get this error:

> /home/patty/Escritorio/Clonados/clone-git/friender/services/feed.js:4
>   nextInFeed: function(req.signedCookies.userId, cb) {
>                           ^
> 
> SyntaxError: Unexpected token .
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:387:25)
>     at Object.Module._extensions..js (module.js:422:10)
>     at Module.load (module.js:357:32)
>     at Function.Module._load (module.js:314:12)
>     at Module.require (module.js:367:17)
>     at require (internal/module.js:16:19)
>     at Object.<anonymous> (/home/patty/Escritorio/Clonados/clone-git/friender/routes/feed.js:4:12)
>     at Module._compile (module.js:413:34)
>     at Object.Module._extensions..js (module.js:422:10)

**Comment by GleisonMv** [comment]
req.cookies

https://www.npmjs.com/package/cookie-parser
